apiVersion: v1
kind: Service
metadata:
  name: prestmit-service
spec:
  selector:
    app: prestmit-app
  type: LoadBalancer #Cluster Node
  ports:
    - protocol: TCP
      port: 3000 # Port exposed by the service is 3000
      targetPort: 80 # Target port is 80 inside the container